CREATE TABLE usuario(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
    cargo VARCHAR(80) NOT NULL,
    matricula VARCHAR(7) UNIQUE NOT NULL,
    senha VARCHAR(150) NOT NULL,
    email VARCHAR(80) NOT NULL UNIQUE,
    tipo_usuario VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
