CREATE TABLE parte_interessada (
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(80) NOT NULL,
    email VARCHAR(80) NOT NULL,
    funcao VARCHAR(80) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
